name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set application.yml
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicdsample
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cicdsample

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SCP Transfer to Remote
        run: scp *.jar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/api

      - name: Restart Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} <<EOF
            echo "▶ Killing existing process on port 8080"
            sudo fuser -k 8080/tcp || true
          
            echo "▶ Starting new JAR"
            cd ~/api
            sudo nohup java -jar *.jar 2>&1 | tee app.log &
          EOF
